name: build-git-installers

on: push

jobs:
  # Check prerequisites for the workflow
  prereqs:
    runs-on: windows-latest
    steps:
      - name: Clone build-extra
        shell: bash
        run: |
          git clone --single-branch -b main https://github.com/git-for-windows/build-extra /usr/src/build-extra
      - name: Update installer metadata for microsoft/git
        shell: bash
        run: |
          b=/usr/src/build-extra &&

          # Remove '.vfs' from version
          version=$(echo ${{ needs.prereqs.outputs.tag_version }} | sed s/.vfs//g) &&

          # Replace AppPublisher and AppVersion with correct values
          sed -i -e "s/^\(AppPublisher=\).*/\1Microsoft/" $b/installer/install.iss &&
          sed -i -e "s/^\(AppVersion=\).*/\1$version/" $b/installer/install.iss &&

          # Add 'ArchitecturesAllowed' and 'LicenseFile' after 'AppVersion'
          sed -i -e '/^AppVersion=.*/a\
          ArchitecturesAllowed=x64 \
          LicenseFile={#SourcePath}\\..\\COPYING \
          ' $b/installer/install.iss
          cat $b/installer/install.iss