name: "release-winget"
on:
  release:
    types: [released]

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Publish manifest with winget-create
        run: |
          # Get correct release asset
          $github = Get-Content '${{ github.event_path }}' | ConvertFrom-Json
          $asset = $github.release.assets | Where-Object -Property name -match '64-bit.exe$'

          # Remove 'v' and 'vfs' from the version
          $github.release.tag_name -match '\d.*'
          $version = $Matches[0] -replace ".vfs",""

          # Download and run wingetcreate
          Invoke-WebRequest https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
        shell: powershell
    
      - name: Publish to test repo
        run: |
          # Point to test repo
          $file = "$env:LOCALAPPDATA\Microsoft\WindowsPackageManagerManifestCreator\settings.json"
          $regex = 'microsoft'
          (Get-Content $file) -replace $regex, 'ldennington' | Set-Content $file
          .\wingetcreate.exe update Microsoft.Git -u $asset.browser_download_url -v $version -o manifests -t "${{ secrets.WINGET_TOKEN }}" -s
        
      - name: action-tmate
        if: failure()
        uses: mxschmitt/action-tmate@v3
