name: "release-winget"
on:
  release:
    types: [released]

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Publish manifest with winget-create
        run: |
          # Get correct release asset
          $github = Get-Content '${{ github.event_path }}' | ConvertFrom-Json
          $asset = $github.release.assets | Where-Object -Property name -match '64-bit.exe$'

          # Remove 'v' and 'vfs' from the version
          $github.release.tag_name -match '\d.*'
          $version = $Matches[0] -replace ".vfs",""

          # Download wingetcreate and create manifests
          Invoke-WebRequest https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          .\wingetcreate.exe update Microsoft.Git -u $asset.browser_download_url -v $version -o manifests

          # Manually substitute the name of the default branch in the License
          # and Copyright URLs since the tooling cannot do that for us.
          $shortenedVersion = $version -replace ".{4}$"
          sed -i '.bak' "s/vfs-[.0-9]*/vfs-$shortenedVersion/g" manifests/*.yaml

          # Submit manifests
          .\wingetcreate.exe submit -t "${{ secrets.WINGET_TEST_TOKEN }}" manifests
        shell: powershell
