name: "release-winget"
on: push

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Get url
        id: get-url
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { data } = await github.repos.getRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: 'latest'
              })
            const assets = data.assets.filter(asset => asset.name.endsWith('.exe'))

            core.setOutput('url', assets[0].url)
            core.setOutput('version', data.tag_name)

      - name: Publish manifest
        run: |
          # Remove 'v' and 'vfs' from the version
          "${{steps.get-url.outputs.version}}" -match '\d.*'
          $version = $Matches[0]

          # Download and run wingetcreate
          iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          .\wingetcreate.exe update Microsoft.Git -u "${{steps.get-url.outputs.url}}" -v $version --out manifests --token "${{ secrets.WINGET_TOKEN }}" --submit
        shell: powershell
