name: Update Homebrew Tap
on:
  release:
    types: [released]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - id: version
      name: Compute version number
      run: |
        echo "::set-output name=result::$(echo $GITHUB_REF | sed -e "s/^refs\/tags\/v//")"
    - id: hash
      name: Compute release asset hash
      uses: mjcheetham/asset-hash@v1
      with:
        asset: /git-(.*)\.pkg/
        hash: sha256
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Update Microsoft Git Cask
      uses: mjcheetham/update-homebrew@v1.2
      with:
        token: ${{ secrets.HOMEBREW_TOKEN }}
        tap: ldennington/homebrew-git
        name: microsoft-git
        type: cask
        version: ${{ steps.version.outputs.result }}
        sha256: ${{ steps.hash.outputs.result }}
