name: test

on:
  workflow_dispatch:
  push:
    branches: [ validate-installers-test ]

jobs:
  windows-playground:
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        component:
          - os: windows-latest
            artifact: win-sign
            command: $PROGRAMFILES\Git\cmd\git.exe
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Indicate full history so Nerdbank.GitVersioning works.

    - name: Install Windows
      if: contains(matrix.component.os, 'windows')
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri https://github.com/microsoft/git/releases/download/v2.36.1.vfs.0.0/Git-2.36.1.vfs.0.0-64-bit.exe -OutFile ./Git-2.36.1.vfs.0.0-64-bit.exe
        Start-Process -Wait -FilePath "./Git-2.36.1.vfs.0.0-64-bit.exe" -ArgumentList "/SILENT /VERYSILENT /NORESTART /SUPPRESSMSGBOXES /ALLOWDOWNGRADE=1"
      
    - name: Validate
      shell: bash
      run: |
        "${{ matrix.component.command }}" --version | sed 's/git version //' >actual
        echo 2.36.1.vfs.0.0 >expect
        cmp expect actual || exit 1
  
    - name: action-tmate
      if: failure()
      uses: mxschmitt/action-tmate@v3
